ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/workflows/**', 'ci/**']
security:
  - changed-files:
      - any-glob-to-any-file: ['bandit.yaml', 'automated_software_developer/security/**']
docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '**/*.md']
core:
  - changed-files:
      - any-glob-to-any-file: ['automated_software_developer/**', 'tests/**']
