"""API service platform adapter."""

from __future__ import annotations

from pathlib import Path

from automated_software_developer.agent.models import RefinedRequirements
from automated_software_developer.agent.platforms.base import PlatformAdapter

API_KEYWORDS = ("api", "endpoint", "rest", "graphql", "service", "backend")


class APIServiceAdapter(PlatformAdapter):
    """Adapter for API-first service projects."""

    adapter_id = "api_service"
    description = "API service adapter for REST/GraphQL services."

    def score(self, refined: RefinedRequirements) -> int:
        """Return heuristic match score for API service requirements."""
        text = _requirements_text(refined)
        score = 1
        score += sum(3 for keyword in API_KEYWORDS if keyword in text)
        if "web" in text:
            score += 1
        return score

    def rationale(self, refined: RefinedRequirements) -> str:
        """Return deterministic rationale for API service selection."""
        return (
            "Selected api_service adapter due to endpoint/service language and "
            "strong backend reliability requirements."
        )

    def supported_deploy_targets(self) -> list[str]:
        """Return deploy targets typically used for API services."""
        return [
            "docker",
            "kubernetes",
            "render",
            "aws",
            "gcp",
            "azure",
            "generic_container_ci",
        ]

    def build_commands(self, project_dir: Path) -> list[str]:
        """Return API build commands based on available project files."""
        if (project_dir / "pyproject.toml").exists():
            return ["python -m compileall -q ."]
        return ["python -m compileall -q ."]

    def package_commands(self, project_dir: Path) -> list[str]:
        """Return packaging commands for API deployment artifacts."""
        if (project_dir / "Dockerfile").exists():
            return ["docker build -t autosd-api:latest ."]
        return ["python -m compileall -q ."]

    def minimum_test_patterns(self) -> list[str]:
        """Return minimum API test patterns for unit and integration tests."""
        return ["tests/test_*.py", "tests/integration/test_*.py"]

    def telemetry_hooks(self) -> list[str]:
        """Return privacy-safe telemetry hooks for API services."""
        return ["request_count", "error_count", "latency_ms_p95"]

    def scaffold_files(self, project_name: str) -> dict[str, str]:
        """Return baseline API adapter scaffold files."""
        return {
            "api/README.md": (
                f"# {project_name} API\n\nAPI service scaffold generated by api_service adapter.\n"
            ),
        }


def _requirements_text(refined: RefinedRequirements) -> str:
    """Return lowercase aggregate text for adapter heuristic scoring."""
    story_text = "\n".join(item.story for item in refined.stories)
    return f"{refined.product_brief}\n{story_text}".lower()
