"""CLI tool platform adapter."""

from __future__ import annotations

from pathlib import Path

from automated_software_developer.agent.models import RefinedRequirements
from automated_software_developer.agent.platforms.base import PlatformAdapter

CLI_KEYWORDS = ("cli", "command", "terminal", "script", "automation")


class CLIToolAdapter(PlatformAdapter):
    """Adapter for command-line tools and automation scripts."""

    adapter_id = "cli_tool"
    description = "CLI tool adapter for terminal-driven workflows."

    def score(self, refined: RefinedRequirements) -> int:
        """Return heuristic match score for CLI-focused requirements."""
        text = _requirements_text(refined)
        score = 1
        score += sum(2 for keyword in CLI_KEYWORDS if keyword in text)
        return score

    def rationale(self, refined: RefinedRequirements) -> str:
        """Return deterministic rationale for CLI adapter selection."""
        return (
            "Selected cli_tool adapter due to command-line automation signals and "
            "low-latency local execution requirements."
        )

    def supported_deploy_targets(self) -> list[str]:
        """Return deploy targets for CLI tooling."""
        return ["pypi", "docker", "github_release", "generic_container_ci"]

    def build_commands(self, project_dir: Path) -> list[str]:
        """Return build commands for CLI project."""
        return ["python -m compileall -q ."]

    def package_commands(self, project_dir: Path) -> list[str]:
        """Return package commands for CLI distribution."""
        if (project_dir / "pyproject.toml").exists():
            return ["python -m build"]
        return ["python -m compileall -q ."]

    def minimum_test_patterns(self) -> list[str]:
        """Return minimum expected CLI test pattern coverage."""
        return ["tests/test_*.py"]

    def telemetry_hooks(self) -> list[str]:
        """Return privacy-safe telemetry hook names for CLI usage."""
        return ["command_invocation_count", "command_error_count", "runtime_ms"]

    def scaffold_files(self, project_name: str) -> dict[str, str]:
        """Return baseline CLI adapter scaffold files."""
        return {
            "cli/README.md": (
                f"# {project_name} CLI\n\nCLI scaffold generated by cli_tool adapter.\n"
            ),
        }


def _requirements_text(refined: RefinedRequirements) -> str:
    """Return lowercase aggregate text for adapter heuristic scoring."""
    story_text = "\n".join(item.story for item in refined.stories)
    return f"{refined.product_brief}\n{story_text}".lower()
