"""Web application platform adapter."""

from __future__ import annotations

from pathlib import Path

from automated_software_developer.agent.models import RefinedRequirements
from automated_software_developer.agent.platforms.base import PlatformAdapter

WEB_KEYWORDS = ("web", "frontend", "browser", "ui", "accessibility", "page")


class WebAppAdapter(PlatformAdapter):
    """Adapter for web application projects with frontend-centric workflows."""

    adapter_id = "web_app"
    description = "Web application adapter (frontend + optional backend)."

    def score(self, refined: RefinedRequirements) -> int:
        """Return heuristic match score for web app requirements."""
        text = _requirements_text(refined)
        score = 1
        score += sum(2 for keyword in WEB_KEYWORDS if keyword in text)
        if "api" in text:
            score += 1
        return score

    def rationale(self, refined: RefinedRequirements) -> str:
        """Return selection rationale for web application stack."""
        return (
            "Selected web_app adapter based on frontend/user-interface signals and "
            "cross-browser delivery needs inferred from refined requirements."
        )

    def supported_deploy_targets(self) -> list[str]:
        """Return deploy targets typically used for web applications."""
        return [
            "github_pages",
            "netlify",
            "vercel",
            "docker",
            "render",
            "generic_container_ci",
        ]

    def build_commands(self, project_dir: Path) -> list[str]:
        """Return build commands based on project file layout."""
        package_json = project_dir / "package.json"
        if package_json.exists():
            return ["npm ci", "npm run build"]
        return ["python -m compileall -q ."]

    def package_commands(self, project_dir: Path) -> list[str]:
        """Return packaging commands for web app artifacts."""
        if (project_dir / "Dockerfile").exists():
            return ["docker build -t autosd-webapp:latest ."]
        return ["python -m compileall -q ."]

    def minimum_test_patterns(self) -> list[str]:
        """Return minimum web project test expectations."""
        return ["tests/test_*.py", "tests/ui/test_*.py"]

    def telemetry_hooks(self) -> list[str]:
        """Return privacy-safe telemetry hook names for web applications."""
        return ["page_view_count", "api_error_count", "request_latency_ms"]

    def scaffold_files(self, project_name: str) -> dict[str, str]:
        """Return baseline web adapter scaffold files."""
        return {
            "frontend/README.md": (
                f"# {project_name} Frontend\n\n"
                "Web UI scaffold generated by web_app adapter.\n"
            ),
        }


def _requirements_text(refined: RefinedRequirements) -> str:
    """Return lowercase aggregate text for adapter heuristic scoring."""
    story_text = "\n".join(item.story for item in refined.stories)
    return f"{refined.product_brief}\n{story_text}".lower()
